UI dev
openairsoft/openmosfet pull request #12
Opened 2021-02-14 13:58 UTC by zaosoula

2021-02-28 16:35 UTC, simonjamain commented
@zaosoula j'ai ajouté `enableSetupScreen` dans la config je te redonne la main, j'ai voulu modifier ton JS mais je m'y prenait pas bien je pense je te laisse faire ça bien

2021-02-28 16:36 UTC, simonjamain requested changes
@zaosoula j'ai ajouté `enableSetupScreen` dans la config je te redonne la main, j'ai voulu modifier ton JS mais je m'y prenait pas bien je pense je te laisse faire ça bien

2021-03-05 22:11 UTC, zaosoula commented
@simonjamain c'est fait 👍

2021-03-06 09:45 UTC, simonjamain commented
@zaosoula je me rappelle plus, on à dit qu'on squash c'est ok ?

2021-03-06 10:29 UTC, simonjamain commented
testé et approuvé, ça marche au poil

2021-03-06 10:29 UTC, merged